version: '3'

services:
  app-calendar:
    build: .
    env_file:
      - .env
    ports:
      - "8088:8088"
    networks:
      - calendar-ihp
    restart: on-failure
    depends_on:
      - pg-16

  pg-16:
    image: postgres:16
    environment:
      - "POSTGRES_DB=${PG_DATABASE}"
      - "POSTGRES_USER=${PG_USER}"
      - "POSTGRES_PASSWORD=${PG_PASSWORD}"
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s